name: CI
on:
  pull_request:
    branches: [ "main" ]
  push:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Enable Corepack
        run: corepack enable

      - name: Yarn install
        run: yarn install

      - name: Biome code check
        run: yarn run lint

      - name: Build
        run: yarn run build

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            lib/**/*.js
            lib/**/*.js.map
            lib/**/*.d.ts
            test/**/*.js
            test/**/*.js.map

  test-nodejs:
    name: Test Node.js (V8)

    runs-on: ${{ matrix.os }}

    needs: build

    env:
      YARN_IGNORE_NODE: 1

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [18.x, 20.x, 22.x]

    steps:

      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install

      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: build

      - name: Test with Node.js ${{ matrix.node-version }}
        run: yarn run test

  test-bum:
    name: Test Bum (JavaScriptCore)
    runs-on: ubuntu-latest

    needs: build

    env:
      YARN_IGNORE_NODE: 1

    strategy:
      matrix:
        bun-version: [1.2]

    steps:

      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ matrix.bun-version }}

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install

      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: build

      - name: Test with Node.js ${{ matrix.node-version }}
        run: bun run --bun test
